CREATE DATABASE LAZADA;
USE LAZADA;

CREATE TABLE LOAISANPHAM(
	MALOAISP INT IDENTITY(1, 1),
    TENLOAISP NVARCHAR(200),
    MALOAI_CHA INT,
    
    CONSTRAINT KHOACHINH_LOAISANPHAM_MALOAI PRIMARY KEY (MALOAISP)
);

CREATE TABLE THUONGHIEU(
	MATH INT IDENTITY(1, 1),
    TENTH NVARCHAR(200),
    HINHTH TEXT,
    LUOTMUA INT,
    
    CONSTRAINT KHOACHINH_THUONGHIEU_MATHUONGHIEU PRIMARY KEY (MATH)
);

CREATE TABLE SANPHAM(
	MASP INT IDENTITY(1, 1),
    TENSP NVARCHAR(200),
    GIA DECIMAL,
    ANHLON TEXT,
    ANHNHO TEXT,
    THONGTIN TEXT,
    SOLUONG INT,
    MALOAISP INT,
    MATH INT,
    LUOTMUA INT,
    
    CONSTRAINT KHOACHINH_SANPHAM_MASP PRIMARY KEY (MASP),
    CONSTRAINT KHOANGOAI_SANPHAM_MALOAISP FOREIGN KEY (MALOAISP) REFERENCES LOAISANPHAM (MALOAISP),
  	CONSTRAINT KHOANGOAI_SANPHAM_MATHUONGHIEU FOREIGN KEY (MATH) REFERENCES THUONGHIEU (MATH)
);

CREATE TABLE LOAINHANVIEN(
	MALOAINV INT IDENTITY(1, 1),
    TENLOAINV NVARCHAR(20),
    
    CONSTRAINT KHOACHINH_LOAINHANVIEN_MALOAINV PRIMARY KEY (MALOAINV)
);

CREATE TABLE NHANVIEN(
	MANV INT IDENTITY(1, 1),
    TENNV NVARCHAR(100),
    TENDN VARCHAR(20),
    MATKHAU VARCHAR(20),
    DIACHI TEXT,
    NGAYSINH VARCHAR(10),
    SODT VARCHAR(12),
    GIOITINH VARCHAR(3),
    CMND VARCHAR(20),
    MALOAINV INT,
    
    CONSTRAINT KHOACHINH_NHANVIEN_MANV PRIMARY KEY (MANV),
    CONSTRAINT KHOANGOAI_NHANVIEN_MALOAINV FOREIGN KEY (MALOAINV) REFERENCES LOAINHANVIEN (MALOAINV)
);

CREATE TABLE DONDATHANG(
	MADH INT IDENTITY(1, 1),
    MANV INT,
    TRANGTHAI VARCHAR(3),
    DIACHIGIAO TEXT,
	NGAYDAT VARCHAR(10),
	NGAYGIAO VARCHAR(10),
    MOTA TEXT,

	CONSTRAINT KHOACHINH_DONDATHANG_MADH PRIMARY KEY (MADH)
);

CREATE TABLE CHITIETDATHANG(
	MADH INT,
	MASP INT,
	SOLUONG INT, 

	CONSTRAINT KHOACHINH_CHITIETHOADON_MADH_MASP PRIMARY KEY (MADH, MASP),
    CONSTRAINT KHOANGOAI_CHITIETHOADON_MADH FOREIGN KEY (MADH) REFERENCES DONDATHANG (MADH),
	CONSTRAINT KHOANGOAI_CHITIETHOADON_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP)
);

CREATE TABLE LOAIKHUYENMAI(
    MALOAIKM INT IDENTITY(1, 1),
	TENLOAIKM VARCHAR(200),
    
    CONSTRAINT KHOACHINH_LOAIKHUYENMAI_MALOAIKM PRIMARY KEY (MALOAIKM)
);

CREATE TABLE CHITIETKHUYENMAI(
    MALOAIKM INT,
    MASP INT,
    NGAYBATDAUKM VARCHAR(10),
    NGAYKETTHUCKM VARCHAR(10),
    PHANTRAMKM VARCHAR(1),
    
    CONSTRAINT KHOACHINH_CHITIETKHUYENMAI_MASP_MAKM PRIMARY KEY (MALOAIKM, MASP),
    CONSTRAINT KHOANGOAI_CHIETIETKUYENMAI_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP),
    CONSTRAINT KHOANGOAI_CHITIETKHUYENMAI_MALOAIKM FOREIGN KEY (MALOAIKM) REFERENCES LOAIKHUYENMAI (MALOAIKM)
);

CREATE TABLE BINHLUAN(
	MABL INT IDENTITY(1, 1),
    MANV INT,
    MASP INT,
    NOIDUNG TEXT,
    NGAYBINHLUAN VARCHAR(10),
    
    CONSTRAINT KHOACHINH_BINHLUAN_MABL PRIMARY KEY (MABL),
    CONSTRAINT KHOANGOAI_BINHLUAN_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV),
    CONSTRAINT KHOANGOAI_BINHLUAN_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP)
);

CREATE TABLE DANHGIA(
    MASP INT,
    MANV INT,
    NOIDUNG TEXT,
    SOSAO VARCHAR(1),
    
    CONSTRAINT KHOACHINH_DANHGIA_MASP_MANV PRIMARY KEY (MASP, MANV),
    CONSTRAINT KHOANGOAI_DANHGIA_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV),
    CONSTRAINT KHOANGOAI_DANHGIA_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP)
);

CREATE TABLE MONGMUON(
	MASP INT,
    MANV INT,
    
    CONSTRAINT KHOACHINH_MONGMUON_MASP_MANV PRIMARY KEY (MASP, MANV),
    CONSTRAINT KHOANGOAI_MONGMUON_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV),
    CONSTRAINT KHOANGOAI_MONGMUON_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP)
);